ARDMK_DIR     		= $(HOME)/devel/Arduino-Makefile
ARDUINO_VERSION		= 190
ARDUINO_DIR		= /usr/share/arduino-nightly
MONITOR_PORT  		= /dev/ttyACM0
BOARDS_TXT		= $(ARDUINO_SKETCHBOOK)/hardware/avr/4.0.2/boards.txt
BOARD_TAG     		= a-star32U4
ARDUINO_LIBS		= a-star-32u4-arduino-library TimerOne arduino_msgpack Servo_Zero Adafruit_NeoPixel Wire EEPROM lsm303-arduino vl53l0x-arduino SoftwareSerial Mecha_QMC5883L
AVRDUDE 		= $(ARDUINO_SKETCHBOOK)/upload.sh
RESET_CMD		= /bin/true
ARDUINO_SKETCHBOOK	= .
#CXXFLAGS += -DDEBUG_SERIAL_ENABLED
include /usr/share/arduino/Arduino.mk